### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by gedw99** [jirenius/resgate#33]
Could you point me to a few links in resgate, client and server JS code to show me the security architecture.

I want to try to I integrate Vault (https://www.vaultproject.io/)  to make it really enterprise extensible.
At least to see what sensible opportunity there is to make it easy and powerful.

Vault has a Web GUI too written in golang which makes it easy to get the hang of:
https://github.com/Caiyeon/goldfish
I think that there is also a Web GUI built into Vault too, but i have not tried it.

**Comment by jirenius** [comment]
I don't know what Vault and Oct is, but I do know the security in the protocol :)

First some general info on security:
* Security is handled using access tokens (or just *token*).
* The token is defined by the service issuing the token. Eg. `{"userId":42,"roles":["dev","admin"]}`
* Tokens can only be issued using a [connection token event](https://github.com/jirenius/resgate/blob/master/docs/res-service-protocol.md#connection-token-event).
* Tokens are often issued as part of an [auth request](https://github.com/jirenius/resgate/blob/master/docs/res-service-protocol.md#auth-request), but may be issued at any time, eg. a "call.adminService.kickUser" method.
* Tokens are stored in Resgate, and are *never* sent to the client.
* Tokens are tied to a connection. If a client reconnects, the previous token is discarded.
* Tokens never expire
* Tokens can at anytime be replaced/removed with a new *connection token event*
* Tokens are included in *access*, *call* and *auth* requests.

As described in the [Gateway Flow document](https://github.com/jirenius/resgate/blob/master/docs/gateway-flow.md), resgate will always make sure an access request is made before  letting a client subscribe, or before making a call request on behalf of the client.

If a new token is issued, resgate will call "access" on any resource currently subscribed by that connect, to verify it still has access with the new token. If not, resgate will unsubscribe the resources.

I will gather a few links to the source code to show these concepts. Soon. ;)

**Comment by gedw99** [comment]
Link to vault and nomad integration.

Nomad is a golbal process runner.
Vault is a global PKI issuer.
Consul is the glue 

https://www.nomadproject.io/docs/vault-integration/index.html

**Comment by goldalworming** [comment]
how about implement jwt, at least only auth user can connect to websocket

**Comment by jirenius** [comment]
Closing topic
